Fix schema

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,109 +8,115 @@ executors:
       NPM_CONFIG_PREFIX: ~/.npm-global
 
 jobs:
-  build_cli:
-    executor: node8
+    build_cli:
+        executor: node8
 
-    steps:
-        # Prepare working env
-        - checkout
-        - run:
-            name: Compute parameters and echo values
-            command: |
-                echo -n "Branch(es) received as parameter: " && [[ ! -z "${GDM_MODULE_BRANCHES}" ]] && echo "${GDM_MODULE_BRANCHES}" || echo "No parameter received - using all master"
-                if [ -z ${GDM_MODULE_BRANCHES} ]; then GDM_MODULE_BRANCHES="{}"; fi
-                cli_branch=$(echo $GDM_MODULE_BRANCHES | jq -r 'if ."helix-cli" then ."helix-cli" else "master" end');
-                echo "Using helix-cli branch: ${cli_branch}"
-                if [ -z ${SMOKETEST_BRANCH} ]; then SMOKETEST_BRANCH="master"; fi
-                echo "Using project-helix.io branch: ${SMOKETEST_BRANCH}"
-                # Require to "pass" variables across steps
-                echo "export GDM_MODULE_BRANCHES=$GDM_MODULE_BRANCHES" >> $BASH_ENV
-                echo "export cli_branch=$cli_branch" >> $BASH_ENV
-                echo "export SMOKETEST_BRANCH=$SMOKETEST_BRANCH" >> $BASH_ENV
+        steps:
+            # Prepare working env
+            - checkout
+            - run:
+                name: Compute parameters and echo values
+                command: |
+                    echo -n "Branch(es) received as parameter: " && [[ ! -z "${GDM_MODULE_BRANCHES}" ]] && echo "${GDM_MODULE_BRANCHES}" || echo "No parameter received - using all master"
+                    if [ -z ${GDM_MODULE_BRANCHES} ]; then GDM_MODULE_BRANCHES="{}"; fi
+                    cli_branch=$(echo $GDM_MODULE_BRANCHES | jq -r 'if ."helix-cli" then ."helix-cli" else "master" end');
+                    echo "Using helix-cli branch: ${cli_branch}"
+                    if [ -z ${SMOKETEST_BRANCH} ]; then SMOKETEST_BRANCH="master"; fi
+                    echo "Using project-helix.io branch: ${SMOKETEST_BRANCH}"
+                    # Require to "pass" variables across steps
+                    echo "export GDM_MODULE_BRANCHES=$GDM_MODULE_BRANCHES" >> $BASH_ENV
+                    echo "export cli_branch=$cli_branch" >> $BASH_ENV
+                    echo "export SMOKETEST_BRANCH=$SMOKETEST_BRANCH" >> $BASH_ENV
 
-        - run:
-            name: Install npm 6.4.1
-            command: sudo npm -g install npm@6.4.1
+            - run:
+                name: Install npm 6.4.1
+                command: sudo npm -g install npm@6.4.1
 
-        - run:
-            name: Prepare test git user
-            command: git config --global user.email "circleci@project-helix.io" && git config --global user.name "CircleCi Build"
+            - run:
+                name: Prepare test git user
+                command: git config --global user.email "circleci@project-helix.io" && git config --global user.name "CircleCi Build"
 
-        - restore_cache:
-            keys:
-            - v3-dependencies-{{ arch }}-continuous-npm-cache
+            - restore_cache:
+                keys:
+                - v3-dependencies-{{ arch }}-continuous-npm-cache
 
-        - run:
-            name: Install Git Dependency Maker tool
-            command: npm install --no-audit --prefer-offline
-            working_directory: scripts/gdm
+            - run:
+                name: Install Git Dependency Maker tool
+                command: npm install --no-audit --prefer-offline
+                working_directory: scripts/gdm
 
-        # Prepare helix-cli to run the smoke tests
-        - run:
-            name: Clone helix-cli
-            command: |
-                git clone --branch $cli_branch --single-branch --depth 1 https://github.com/adobe/helix-cli.git
-        
-        - run:
-            name: Install using git branches (master or specified)
-            command: env GDM_MODULE_BRANCHES=$GDM_MODULE_BRANCHES node ../scripts/gdm/index.js
-            working_directory: helix-cli
+            # Prepare helix-cli to run the smoke tests
+            - run:
+                name: Clone helix-cli
+                command: |
+                    git clone --branch $cli_branch --single-branch --depth 1 https://github.com/adobe/helix-cli.git
+            
+            - run:
+                name: Install using git branches (master or specified)
+                command: env GDM_MODULE_BRANCHES=$GDM_MODULE_BRANCHES node ../scripts/gdm/index.js
+                working_directory: helix-cli
 
     test_project_helix:
         executor: node8
-        # Checkout project-helix.io
-        - run:
-            name: Clone project-helix.io
-            command: |
-                git clone --single-branch --depth 1 -b ${SMOKETEST_BRANCH} https://github.com/adobe/project-helix.io.git
 
-        - run:
-            name: Install project-helix.io
-            command: npm install --no-audit --prefer-offline
-            working_directory: project-helix.io
+        steps:
+            # Checkout project-helix.io
+            - run:
+                name: Clone project-helix.io
+                command: |
+                    git clone --single-branch --depth 1 -b ${SMOKETEST_BRANCH} https://github.com/adobe/project-helix.io.git
 
-        # Run the smoke tests
-        - run:
-            name: Run Smoke Tests on project-helix.io
-            command: env HLX_SMOKE_EXEC='node ../helix-cli/index.js --log-level warn' npx mocha --exit test/smoke/*
-            working_directory: project-helix.io
+            - run:
+                name: Install project-helix.io
+                command: npm install --no-audit --prefer-offline
+                working_directory: project-helix.io
+
+            # Run the smoke tests
+            - run:
+                name: Run Smoke Tests on project-helix.io
+                command: env HLX_SMOKE_EXEC='node ../helix-cli/index.js --log-level warn' npx mocha --exit test/smoke/*
+                working_directory: project-helix.io
 
     test_helix_cli:
         executor: node8
-        # Run the hlx-cli (last step because they might fail for good reason - tests upgrade required, non-backward comp... )
-        - run: mkdir junit
-        
-        - run:
-            name: Test helix-cli
-            command: npm run test
-            working_directory: helix-cli
-            environment:
-                MOCHA_FILE: junit/test-results.xml
 
-        - store_test_results:
-            path: junit
+        steps:
+            # Run the hlx-cli (last step because they might fail for good reason - tests upgrade required, non-backward comp... )
+            - run: mkdir junit
+            
+            - run:
+                name: Test helix-cli
+                command: npm run test
+                working_directory: helix-cli
+                environment:
+                    MOCHA_FILE: junit/test-results.xml
 
-        - store_artifacts:
-            path: junit
+            - store_test_results:
+                path: junit
+
+            - store_artifacts:
+                path: junit
 
     finalize:
-        - save_cache:
-            executor: node8
-            paths:
-            - /home/circleci/.npm
-            key: v3-dependencies-{{ arch }}-continuous-npm-cache
+        executor: node8
+        steps:
+            - save_cache:
+                paths:
+                - /home/circleci/.npm
+                key: v3-dependencies-{{ arch }}-continuous-npm-cache
+
 workflows:
-  version: 2
-  build:
-    jobs:
-    - build_cli
-    - test_project_helix
-        requires:
-        - build_cli
-    - test_helix_cli
-        requires:
-        - build_cli
-    - finalize
-        requires:
-        - test_project_helix
-        - test_helix_cli
+    version: 3
+    build:
+        jobs:
+            - build_cli
+            - test_project_helix:
+                requires:
+                - build_cli
+            - test_helix_cli:
+                requires:
+                - build_cli
+            - finalize:
+                requires:
+                - test_project_helix
+                - test_helix_cli
